services:
  postgres:
    image: postgres:16-alpine
    container_name: sa_postgres
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - sa_pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB || exit 1"]
      interval: 5s
      timeout: 3s
      retries: 20

  api:
    image: node:20-alpine
    container_name: sa_api
    working_dir: /usr/src/app
    env_file:
      - .env
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - "${PORT:-3000}:3000"
    command: sh -c "npm ci && npm run start:dev"
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules

volumes:
  sa_pgdata:
