version: "3.8"

services:
  postgres:
    image: postgres:16-alpine
    container_name: sa_postgres
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - sa_pgdata:/var/lib/postgresql/data
    env_file:
      - .env

  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: sa_api
    env_file:
      - .env
    depends_on:
      - postgres
    ports:
      - "${PORT:-3000}:3000"
    command: npm run start:dev
    volumes:
      - ./:/app
      - /app/node_modules

volumes:
  sa_pgdata:
