version: "3.8"

services:
  postgres:
    image: postgres:16-alpine
    container_name: sa_postgres
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - sa_pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB || exit 1"]
      interval: 5s
      timeout: 3s
      retries: 20
    env_file:
      - .env

  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: sa_api
    working_dir: /app
    env_file:
      - .env
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - "${PORT:-8080}:${PORT:-8080}"
    command: npm run start:dev
    volumes:
      - ./:/app
      - /app/node_modules

volumes:
  sa_pgdata:
