version: "3.8"
services:
  postgres:
    image: postgres:16-alpine
    container_name: sa_postgres
    environment:
      POSTGRES_DB: string_analyzer
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - sa_pgdata:/var/lib/postgresql/data
  api:
    build: .
    container_name: sa_api
    env_file: .env
    depends_on:
      - postgres
    ports:
      - "${PORT:-3000}:3000"
    command: npm run start:dev
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules
volumes:
  sa_pgdata:
